/** Designer-facing explanations, separate from canonical tuning values. */
export function label(key: string): string {
  return key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/_/g, ' ').replace(/^./, c => c.toUpperCase());
}
const help: Record<string, string> = {
  militaryBehavior: 'War preparation, target preferences, and required military readiness for this era strategy.',
  foundingRules: 'Constraints on voluntary settlement placement.',
  resourcePriorities: 'Relative priority of sea resource exploitation and work boat production.',
  tilePurchase: 'Treasury and scoring thresholds for discretionary tile acquisition.',
  happinessBehavior: 'Thresholds that trigger happiness stabilization and emergency measures.',
  cityFocusRules: 'City specialization and population thresholds for focus changes.',
  productionRhythm: 'How many units can be built consecutively before favoring infrastructure.',
  military: 'Unit limits, target reach, attack health, and tactical aggression for this base strategy.',
  expansion: 'City goals and settler spacing/timing for this base strategy.',
  production: 'Production category scores and infrastructure need thresholds for this base strategy.',
  navalExpeditions: 'Enables planning naval expeditions against enemies during war. Previously specific to Naval Power.',
  navalSaturationControl: 'Reduces naval production urgency when fleet size exceeds coastal-city and active-war needs. Previously specific to Naval Power.',
  strategyBias: 'Adds points to the named base strategy during situation-based selection. Positive favors it; negative discourages it. These are scores, not percentages.',
  productionWeights: 'Relative production scoring weights. Higher values favor this unit or building category; actual availability and economic constraints still apply.',
  researchWeights: 'Relative research scoring weights for technologies that support each goal. Higher values favor that goal.',
  cultureWeights: 'Relative culture selection weights for these goals. Higher values favor matching unlocks.',
  diplomacyWeights: 'Multipliers for diplomatic action scores. Higher values favor the action; they do not guarantee acceptance.',
  preferredRoles: 'Multipliers on unit production scores by military role. 1 is neutral; larger values favor this role.',
  targetComposition: 'Desired fraction of the army in this role (0–1). Role deficits influence unit production scores.',
  militaryBudget: 'Controls desired army strength and unit ceilings relative to normal strategic needs.',
  strategicTolerance: 'Economic and happiness conditions under which military production may continue.',
  productionBehavior: 'Relative preference for upgrading units, inexpensive quantity, or stronger quality.',
  foundingPreferences: 'Relative settlement-site scoring weights. Positive weights value this feature; distance penalty discourages remote sites.',
  covertUsageBias: 'Propensity to initiate covert operations, roughly −1 (avoids) to +1 (favors). Some covert preferences are reserved for future mission selection.',
  suspicionSensitivity: 'Multiplier on suspicion gained as a victim. Values above 1 make accusations accumulate faster.',
  riskTolerance: 'Tolerance for covert diplomatic blowback: around 0.5 cautious to 1.5 reckless.',
  proxyWarPreference: 'Preference for proxy/covert pressure over open war (0–1).',
  espionagePreference: 'Preference for spy/agent operations (0–1); reserved for future covert AI selection.',
  suspicionToWar: 'Multiplier converting suspicion into willingness to go to war; 1 is baseline.',
  suspicionToTrade: 'Multiplier converting suspicion into reluctance to trade; 1 is baseline.',
  diplomacyBias: 'Bias to diplomatic cooperation. Higher values favor cooperation.',
  tradeBias: 'Bias to trade acceptance. Higher values favor trade.',
  warBias: 'Bias to war willingness. Higher values favor war.',
  openBordersBias: 'Bias to open-border agreements. Higher values favor access.',
  cultureResistance: 'Resistance to foreign cultural pressure. Higher values increase resistance.',
  expansionBias: 'Bias to territorial expansion. Higher values favor expansion.',
  strengthMultiplier: 'Multiplies desired military strength. 1 is neutral; prestige projection deliberately aims for a larger army.',
  maxUnitsMultiplier: 'Multiplies the normal unit cap. 1 is neutral.',
  allowOverbuildingWhenThreatened: 'Allows exceeding the normal military budget when threats justify it.',
  minHappinessForMilitaryBuilds: 'Minimum national happiness for discretionary military production.',
  minGoldReserveForMilitaryBuilds: 'Minimum treasury reserve for discretionary military production.',
  tolerateWarWeariness: 'Allows military production despite war weariness.',
  modernizationBias: 'Favors modernizing the army. The production behavior block is authoritative; the top-level field is a legacy mirror.',
  quantityBias: 'Favors greater numbers of units. The production behavior block is authoritative; the top-level field is a legacy mirror.',
  qualityBias: 'Favors higher-quality units. The production behavior block is authoritative; the top-level field is a legacy mirror.',
  prepareForWar: 'Enables preparation for a future war.',
  targetWeakNeighbor: 'Prefers militarily weak neighbors when evaluating targets.',
  preferCapitalTargets: 'Favors enemy capitals as military objectives.',
  minimumMilitaryReadiness: 'Minimum readiness ratio for planned military action; higher requires more preparation.',
  minCityDistance: 'Minimum spacing between founded cities in map tiles.',
  seaResourceExploitation: 'Multiplier favoring exploitation of sea resources.',
  workBoatProduction: 'Multiplier favoring work boat production.',
  minGoldReserve: 'Gold that must remain available before discretionary tile purchases.',
  minScore: 'Minimum site score required for a tile purchase.',
  stabilizationThreshold: 'Happiness level below which stabilization becomes a priority.',
  criticalThreshold: 'Happiness level considered critical for emergency stabilization.',
  primaryCityFocus: 'Preferred specialization for city production and development.',
  largeCityPopulationThreshold: 'Population at which large-city focus rules apply.',
  peaceUnitsBeforeInfrastructure: 'Consecutive units allowed before favoring infrastructure during peace.',
  warUnitsBeforeInfrastructure: 'Consecutive units allowed before favoring infrastructure during war.',
  maxUnits: 'Normal military unit ceiling before doctrine and situational modifiers.',
  minAttackHealthRatio: 'Minimum remaining health fraction for attacks (0–1).',
  engageDistance: 'Maximum target engagement distance in map tiles.',
  preferReachableTargets: 'Prioritizes targets that pathfinding considers reachable.',
  randomnessFactor: 'Amount of random variation in military decisions.',
  aggression: 'Military aggression multiplier: 0.5 defensive, 1 neutral, 2 aggressive. In behavior weights, controls aggressive action scoring.',
  desiredCityCount: 'Desired number of cities. A leader city limit can further cap voluntary expansion.',
  settlerMinCityDistance: 'Minimum settlement distance in map tiles.',
  settlerInterval: 'Turns between settler production opportunities.',
  lowNetFoodThreshold: 'Net food threshold that triggers food infrastructure priorities.',
  lowProductionThreshold: 'Production threshold that triggers production infrastructure priorities.',
  exploration: 'Exploration action weight; larger values favor scouting.',
  diplomacy: 'Diplomatic action weight; larger values favor diplomatic activity.',
  trade: 'Trade activity weight: 0 disables deals, below 2 allows one deal per turn, 2+ allows two.',
  defense: 'Defensive action weight; larger values favor defense.',
};
export function parameterHelp(path: string): string {
  const parts = path.split('.');
  return help[parts[parts.length - 1]] ?? parts.map(p => help[p]).find(Boolean)
    ?? (path.includes('Weight') ? 'Relative production score. Higher values favor this category.' : 'Finite tuning value. Effects combine with current conditions and other configuration layers.');
}
