import path from 'node:path';
import { build } from 'esbuild';

/**
 * Bundles the shared natural-resource generator into a browser-loadable IIFE for
 * the standalone Scenario Editor (public/editor.html). The editor is a plain
 * static HTML file with no module system, so it consumes this committed bundle
 * via a classic <script> tag. The canonical generation logic stays in
 * src/systems/NaturalResourceSystem.ts — this only re-packages it, never forks it.
 */

const projectRoot = path.resolve(process.cwd());
const entryPoint = path.join(projectRoot, 'src', 'editor', 'editorResourceGenerationBundle.ts');
const outfile = path.join(projectRoot, 'public', 'editor', 'epoch-editor-resources.js');

await build({
  entryPoints: [entryPoint],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  legalComments: 'none',
  banner: {
    js: '/* Generated by scripts/generateEditorResourceBundle.ts — do not edit by hand. */',
  },
});

// eslint-disable-next-line no-console
console.log(`Editor resource generator bundle written to ${path.relative(projectRoot, outfile)}`);
