import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH ?? '/usr/bin/google-chrome', args: ['--no-sandbox'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${process.env.EPOCH_EDITOR_URL ?? 'http://127.0.0.1:5174'}/editor.html`);
  await page.waitForFunction(() => typeof window.EpochLeaderEditor?.open === 'function');
  await page.waitForFunction(() => document.querySelector('#landing-create-btn') || document.querySelector('#landing'));
  await page.evaluate(() => {
    const data = buildBlankScenario('Leader browser test', ['nation_india'], 4, 4, 32, null);
    window.editorTestScenario = data;
    startEditor({ label: 'Leader browser test', file: 'leader-test.json', isNew: true }, data, null);
  });
  await page.getByRole('button', { name: 'Leaders & AI', exact: true }).click();
  const dialog = page.locator('dialog.le-dialog');
  await dialog.locator('.le-side input').fill('gandhi');
  await dialog.getByRole('button', { name: 'Gandhi', exact: true }).click();
  assert.equal(await dialog.getByLabel('Opportunism', { exact: true }).isChecked(), false);
  await dialog.getByLabel('Opportunism', { exact: true }).check();
  assert.equal(await dialog.getByLabel('Impulsive Bully', { exact: true }).isChecked(), false);
  await dialog.getByLabel('Impulsive Bully', { exact: true }).check();
  await dialog.getByLabel('Aggression', { exact: true }).fill('20');
  await dialog.getByLabel('Aggression', { exact: true }).press('Tab');
  assert.match(await dialog.locator('.le-summary').first().innerText(), /Aggressive/);
  await dialog.getByText('Era Strategy', { exact: true }).click();
  await dialog.getByLabel('Modern', { exact: true }).selectOption('militaryPreparation');
  assert.match(await dialog.innerText(), /Inherited from modern/);
  await dialog.locator('.le-head select').selectOption('doctrines');
  await dialog.locator('.le-side input').fill('naval power');
  await dialog.getByRole('button', { name: 'Naval Power', exact: true }).click();
  await dialog.getByLabel('New variant ID').fill('scenario_naval');
  await dialog.getByRole('button', { name: 'Duplicate / Create Variant', exact: true }).click();
  assert.match(await dialog.innerText(), /used by 0 leaders/);
  await dialog.locator('.le-head select').selectOption('leaders');
  await dialog.locator('.le-side input').fill('gandhi');
  await dialog.getByRole('button', { name: 'Gandhi', exact: true }).click();
  await dialog.getByLabel('Doctrines', { exact: true }).selectOption('scenario_naval');
  await dialog.getByRole('button', { name: /Inspect Naval Power Variant/ }).click();
  assert.match(await dialog.innerText(), /used by 1 leaders/);
  await dialog.getByRole('button', { name: 'Apply to Scenario', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  assert.deepEqual(errors, []);
  const saved = await page.evaluate(() => ({ applied: !document.querySelector('dialog.le-dialog[open]'), config: buildScenarioOutput().leaderConfiguration }));
  assert.equal(saved.applied, true);
  assert.equal(saved.config.leaders['leader_mahatma-gandhi'].aiPersonality.aggressionBias, 20);
  assert.equal(saved.config.leaders['leader_mahatma-gandhi'].opportunism, true);
  assert.equal(saved.config.leaders['leader_mahatma-gandhi'].impulsiveBully, true);
  assert.equal(saved.config.profiles.doctrines[0].navalExpeditions, true);
  assert.deepEqual(Object.keys(saved.config.eraAssignments['leader_mahatma-gandhi']), ['ancient', 'modern']);
  await page.evaluate(() => window.EpochLeaderEditor.open(window.editorTestScenario, () => {}));
  await page.locator('dialog.le-dialog .le-side input').fill('gandhi');
  await page.locator('dialog.le-dialog').getByRole('button', { name: 'Gandhi', exact: true }).click();
  await page.screenshot({ path: '/tmp/epoch-leader-editor.png' });
  await page.locator('dialog.le-dialog').getByLabel('Aggression', { exact: true }).fill('999');
  await page.locator('dialog.le-dialog').getByLabel('Aggression', { exact: true }).press('Tab');
  await page.locator('dialog.le-dialog').getByRole('button', { name: 'Apply to Scenario', exact: true }).click();
  assert.match(await page.locator('.le-errors').innerText(), /invalid personality aggressionBias/);
  await page.locator('dialog.le-dialog').getByRole('button', { name: 'Discard / Close', exact: true }).click();
  assert.equal((await page.evaluate(() => window.editorTestScenario.leaderConfiguration)).leaders['leader_mahatma-gandhi'].aiPersonality.aggressionBias, 20);
  assert.deepEqual(errors, []);
  console.log('Leader editor browser workflow passed. Screenshot: /tmp/epoch-leader-editor.png');
} finally { await browser.close(); }
